### ISSUE TITLE
[question] Why you don't have to unmock the react-with-context module

### ISSUE THREAD

**Issue by lpan** [mattzeunert/react-with-context-demo#1]
Why react-with-context is not mocked in [package.json(https://github.com/mattzeunert/react-with-context-demo/blob/master/package.json#L25-L28)

Thanks :)

**Comment by mattzeunert** [comment]
It took me a while to figure this out, ended up adding logging to the Jest code.

The `unmockedModulePathPatterns` are regular expressions, so `"<rootDir>/node_modules/react"` matches `react-dom` and `react-addons-test-utils` as well, so it's not required to list them separately.

`"<rootDir>/node_modules/react"` also matches `react-with-context`, so the module isn't mocked, even though it's not explicitly listed.

**Comment by lpan** [comment]
thanks a lot for the explanation matt! :)
